sudo: false
language: python
cache: pip

addons:
  apt:
    packages:
      - pandoc

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - 3.8-dev

env:
  matrix:

matrix:
  allow_failures:
    - python: 3.8-dev
  include:

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install mock; fi
  - pip install coverage codecov

script:
  - coverage run -m unittest discover

after_success:
  - codecov

before_deploy:
  - pip install wheel
  - pandoc --from=markdown --to=rst --output=README.rst README.md
  - python setup.py sdist bdist_wheel

deploy:
